### ISSUE TITLE
Build failing with the steps given. Related to Tera

### ISSUE THREAD

**Issue by nguiard** [Cahu/krpc-mars#1]
Hi,
I'm trying to use krpc-mars. I followed exactly the steps given in the README, but the build fails with:

<pre>
error: failed to run custom build command for `betterjeb v0.1.0 (/home/nicolas/Projects/rust-testing/betterjeb)`
process didn't exit successfully: `/home/nicolas/Projects/rust-testing/betterjeb/target/debug/build/betterjeb-dcc88ac2ae171836/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=services/KRPC.Drawing.json
cargo:rerun-if-changed=services/KRPC.InfernalRobotics.json
cargo:rerun-if-changed=services/KRPC.KerbalAlarmClock.json
cargo:rerun-if-changed=services/KRPC.RemoteTech.json
cargo:rerun-if-changed=services/KRPC.SpaceCenter.json
cargo:rerun-if-changed=services/KRPC.UI.json

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Msg("Template `service.rs` loads macros from `macros.tera` which isn\'t present in Tera"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })',
src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
</pre>
Seems like Tera doesn't see macros.tera in krpc-mars-terraformer... I haven't dived into it but maybe you'd know of a simple fix?
Cheers.

**Comment by imjasonmiller** [comment]
Did you ever manage to solve this @nguiard? I am unfortunately running into the same error:

```
error: failed to run custom build command for `betterjeb v0.1.0 (/mnt/d/work/2019/betterjeb)`
Caused by:
process didn't exit successfully: `/mnt/d/work/2019/betterjeb/target/debug/build/betterjeb-a36feba5679404d2/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=services/KRPC.Drawing.json
cargo:rerun-if-changed=services/KRPC.InfernalRobotics.json
cargo:rerun-if-changed=services/KRPC.KerbalAlarmClock.json
cargo:rerun-if-changed=services/KRPC.RemoteTech.json
cargo:rerun-if-changed=services/KRPC.SpaceCenter.json
cargo:rerun-if-changed=services/KRPC.UI.json
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(
    Msg("Template `service.rs` loads macros from `macros.tera` which isn\'t present in Tera"),
    State {
        next_error: None,
        backtrace: InternalBacktrace { backtrace: None }
    }
)', 
src/libcore/result.rs:999:5 
```

```sh
.
+-- Cargo.lock
+-- Cargo.toml
+-- build.rs
+-- services
|     +-- KRPC.Drawing.json
|     +-- KRPC.InfernalRobotics
|     +-- KRPC.KerbalAlarmClock.json
|     +-- KRPC.RemoteTech.json
|     +-- KRPC.SpaceCenter.json
|     +-- KRPC.UI.json
+-- src
|     +-- lib.rs
|     +-- main.rs
```
I'm currently looking at the [`tera`](https://github.com/Keats/tera) package.

**Comment by Cahu** [comment]
Should be fixed by https://github.com/Cahu/krpc-mars-terraformer/pull/1

**Comment by imjasonmiller** [comment]
It now works on my end @Cahu. Thank you! 🚀
