### ISSUE TITLE
krpc-mars fails to build 

### ISSUE THREAD

**Issue by Galileo-dev** [Cahu/krpc-mars#2]
PS D:\Games\LandingRockets\KRPC\betterjeb> cargo build 
   Compiling krpc_mars v0.7.0 (https://github.com/Cahu/krpc-mars#545ab084)
error: failed to run custom build command for `krpc_mars v0.7.0 (https://github.com/Cahu/krpc-mars#545ab084)`

Caused by:
  process didn't exit successfully: `D:\Games\LandingRockets\KRPC\betterjeb\target\debug\build\krpc_mars-ee669842f05d2e56\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=protos/krpc.proto
  cargo:rerun-if-changed=src/krpc.rs

  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', C:\Users\galileo\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-2.17.0\src\lib.rs:203:17
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/755064bef62d3c1a6793ef9d87e112489ad579c9\/library\std\src\panicking.rs:475
     1: std::panicking::begin_panic_fmt
               at /rustc/755064bef62d3c1a6793ef9d87e112489ad579c9\/library\std\src\panicking.rs:429
     2: protoc::Protoc::from_env_path
               at C:\Users\galileo\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-2.17.0\src\lib.rs:203
     3: protoc_rust::Codegen::run
               at C:\Users\galileo\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-rust-2.17.0\src\lib.rs:151
     4: protoc_rust::run
               at C:\Users\galileo\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-rust-2.17.0\src\lib.rs:215
     5: build_script_build::main
               at .\build.rs:6
     6: core::ops::function::FnOnce::call_once<fn(),tuple<>>
               at C:\Users\galileo\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
PS D:\Games\LandingRockets\KRPC\betterjeb>

**Comment by Cahu** [comment]
Hi,

As you can see from the error, the problem is the protoc-rust library is unable to find the protoc binary (see https://github.com/stepancheg/rust-protobuf/tree/master/protoc-rust for instructions).

**Comment by Galileo-dev** [comment]
Thanks
