### ISSUE TITLE
"Protocol message contained an invalid tag (zero)" Errors when attempting to send calls w/ tuple arguments.

### ISSUE THREAD

**Issue by drwhomphd** [Cahu/krpc-mars#4]
Currently, with KRPC v0.48 I'm getting the `Error receiving request from client 172.23.157.229: Protocol message contained an invalid tag (zero).` error when leveraging the following Tuple-argumented RPCs:
space_center::transform_direction
planet.latitude_at_position
planet.longitude_at_position
planet.altitude_at_position

Where planet refers to the orbital body the vessel is currently orbiting.

I believe it's related to how Tuple arguments are getting encoded prior to being sent, but I'm not familiar enough with the krpc-mars codebase nor protobuf to determine the exact issue. I did notice they aren't being packaged into the KRPC protobuf generated Tuple type as is done in the C++ library if that matters. Having compared krpc-mars packets in wireshark vs krpc-python packets, I do see a difference in the way krpc-mars is encoding the tuple argument in both length and content.

RPCs with floats and other service based references are encoding fine and work as expected.

**Comment by drwhomphd** [comment]
I believe the following implementation for three-tuples fixed the issue:
```
impl<T, U, V> RPCEncodable for (T, U, V)
    where T: RPCEncodable,
          U: RPCEncodable,
          V: RPCEncodable
{
    fn encode(&self, output: &mut protobuf::CodedOutputStream) -> Result<(), protobuf::ProtobufError> {
        let &(ref t, ref u, ref v) = self;
        let mut tuple = krpc::Tuple::new();
        tuple.items.push(t.encode_to_bytes()?);
        tuple.items.push(u.encode_to_bytes()?);
        tuple.items.push(v.encode_to_bytes()?);
        tuple.write_to(output)?;
        Ok(())
    }
}
```

**Comment by Cahu** [comment]
Thanks for catching this @drwhomphd.
I'm reviving this project. Your fix will be included in the next release !

**Comment by Cahu** [comment]
In #6
